# Generated by Django 3.2.19 on 2023-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='studentID',
            field=models.IntegerField(),
        ),
    ]
