# Generated by Django 3.2.19 on 2023-06-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('studentID', models.IntegerField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('orderItem', models.CharField(max_length=200)),
            ],
        ),
    ]
