# Generated by Django 3.2.19 on 2023-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_order_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('orderItem', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('remainder', models.IntegerField()),
            ],
        ),
    ]
